version: '3'
services:
  maildev:
    image: maildev/maildev
    container_name: maildev_health-care
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8081:80
      - 25:25
#    restart: always
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_health-care
#    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_POST: 3307
      PMA_HOST: mysql
      UPLOAD_LIMIT: 64M
    networks:
      - dev

  mysql:
    image: mysql
    container_name: mysql_health-care
    command: mysqld --default-authentication-plugin=mysql_native_password
#    restart: always
    ports:
      - 3307:3306
    volumes:
      - db-data-mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: health-care
    networks:
      - dev

  strapi:
    container_name: strapi_health-care
    build:
      context: .
      dockerfile: Dockerfile-back
    volumes:
      - ./back:/app
#    restart: always
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: health-care
      DATABASE_USERNAME: root
      DATABASE_PASSWORD:
    ports:
      - 1337:1337
    depends_on:
      - mysql
    networks:
      - dev

  front:
    container_name: front_health-care
    build:
      context: .
      dockerfile: Dockerfile-front
    volumes:
      - ./front:/app
#    restart: always
    ports:
      - 3000:3000
    depends_on:
      - strapi
    networks:
      - dev

networks:
  dev:

volumes:
  db-data-mysql: